/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  storeName?: string;
  supportEmail?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialLinks?: {
    instagram?: string;
    facebook?: string;
    youtube?: string;
    twitter?: string;
  };
  footerTagline?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type HeroContent = {
  _id: string;
  _type: "heroContent";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  eyebrow?: string;
  heading: string;
  subtext?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  ctaText?: string;
  ctaLink?: string;
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  clerkUserId?: string;
  customerInfo?: {
    name?: string;
    email?: string;
    phone?: string;
    address?: {
      line1?: string;
      line2?: string;
      city?: string;
      state?: string;
      pincode?: string;
      country?: string;
    };
  };
  lineItems?: Array<{
    productId?: string;
    productName?: string;
    colorVariant?: string;
    colorVariantSlug?: string;
    size?: string;
    qty?: number;
    priceSnapshot?: number;
    sku?: string;
    _key: string;
  }>;
  subtotal?: number;
  shippingCost?: number;
  total?: number;
  currency?: string;
  paymentStatus?: "pending" | "paid" | "failed" | "refunded";
  status?:
    | "pending"
    | "paid"
    | "processing"
    | "shipped"
    | "delivered"
    | "cancelled"
    | "refunded";
  razorpayOrderId?: string;
  paymentId?: string;
  razorpaySignature?: string;
  createdAt?: string;
  updatedAt?: string;
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  price: number;
  compareAtPrice?: number;
  colorVariants: Array<
    {
      _key: string;
    } & ColorVariant
  >;
  category?: CategoryReference;
  tags?: Array<string>;
  featured?: boolean;
  seo?: SeoFields;
};

export type SeoFields = {
  _type: "seoFields";
  metaTitle?: string;
  metaDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
};

export type ColorVariant = {
  _type: "colorVariant";
  name: string;
  hex?: string;
  slug: Slug;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  sizes: Array<
    {
      _key: string;
    } & SizeEntry
  >;
};

export type SizeEntry = {
  _type: "sizeEntry";
  size: "XS" | "S" | "M" | "L" | "XL" | "XXL";
  stock: number;
  sku?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | SanityImageCrop
  | SanityImageHotspot
  | HeroContent
  | Order
  | CategoryReference
  | Product
  | SeoFields
  | Slug
  | Category
  | ColorVariant
  | SizeEntry
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: HERO_CONTENT_QUERY
// Query: *[_type == "heroContent" && _id == "heroContent-singleton"][0]{    _id,    eyebrow,    heading,    subtext,    backgroundImage,    ctaText,    ctaLink  }
export type HERO_CONTENT_QUERY_RESULT = {
  _id: "heroContent-singleton";
  eyebrow: string | null;
  heading: string;
  subtext: string | null;
  backgroundImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  ctaText: string | null;
  ctaLink: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: FEATURED_PRODUCTS_QUERY
// Query: *[_type == "product" && featured == true] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    price,    compareAtPrice,    "colorVariants": colorVariants[]{      _key,      name,      hex,      "slug": slug.current,      images[]{ _type, asset, hotspot, alt },      sizes[]{ _key, size, stock }    }  }
export type FEATURED_PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  compareAtPrice: number | null;
  colorVariants: Array<{
    _key: string;
    name: string;
    hex: string | null;
    slug: string;
    images: Array<{
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
    }>;
    sizes: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock: number;
    }>;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_QUERY
// Query: *[_type == "product"] | order(_createdAt desc) {    _id,    name,    "slug": slug.current,    price,    compareAtPrice,    featured,    "colorVariants": colorVariants[]{      _key,      name,      hex,      "slug": slug.current,      images[]{ _type, asset, hotspot, alt },      sizes[]{ _key, size, stock }    },    "category": category->{ _id, name, "slug": slug.current }  }
export type PRODUCTS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  price: number;
  compareAtPrice: number | null;
  featured: boolean | null;
  colorVariants: Array<{
    _key: string;
    name: string;
    hex: string | null;
    slug: string;
    images: Array<{
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
    }>;
    sizes: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock: number;
    }>;
  }>;
  category: {
    _id: string;
    name: string;
    slug: string;
  } | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == "product" && slug.current == $slug][0]{    _id,    name,    "slug": slug.current,    description,    price,    compareAtPrice,    featured,    colorVariants[]{      _key,      name,      hex,      "slug": slug.current,      images[]{ _type, asset, hotspot, alt },      sizes[]{ _key, size, stock, sku }    },    "category": category->{ _id, name, "slug": slug.current },    tags,    seo{ metaTitle, metaDescription, ogImage }  }
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  name: string;
  slug: string;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  price: number;
  compareAtPrice: number | null;
  featured: boolean | null;
  colorVariants: Array<{
    _key: string;
    name: string;
    hex: string | null;
    slug: string;
    images: Array<{
      _type: "image";
      asset: SanityImageAssetReference | null;
      hotspot: SanityImageHotspot | null;
      alt: string | null;
    }>;
    sizes: Array<{
      _key: string;
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock: number;
      sku: string | null;
    }>;
  }>;
  category: {
    _id: string;
    name: string;
    slug: string;
  } | null;
  tags: Array<string> | null;
  seo: {
    metaTitle: string | null;
    metaDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ALL_PRODUCT_SLUGS_QUERY
// Query: *[_type == "product" && defined(slug.current)]{ "slug": slug.current }
export type ALL_PRODUCT_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type == "category"] | order(name asc) {    _id,    name,    "slug": slug.current,    description  }
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  slug: string;
  description: string | null;
}>;

// Source: sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings" && _id == "siteSettings-singleton"][0]{    _id,    storeName,    supportEmail,    logo,    socialLinks,    footerTagline  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: "siteSettings-singleton";
  storeName: string | null;
  supportEmail: string | null;
  logo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  socialLinks: {
    instagram?: string;
    facebook?: string;
    youtube?: string;
    twitter?: string;
  } | null;
  footerTagline: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: PRODUCTS_BY_IDS_QUERY
// Query: *[_type == "product" && _id in $ids]{    _id,    name,    price,    compareAtPrice,    "colorVariants": colorVariants[]{      _key,      name,      "slug": slug.current,      sizes[]{ size, stock, sku }    }  }
export type PRODUCTS_BY_IDS_QUERY_RESULT = Array<{
  _id: string;
  name: string;
  price: number;
  compareAtPrice: number | null;
  colorVariants: Array<{
    _key: string;
    name: string;
    slug: string;
    sizes: Array<{
      size: "L" | "M" | "S" | "XL" | "XS" | "XXL";
      stock: number;
      sku: string | null;
    }>;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: ORDER_BY_NUMBER_QUERY
// Query: *[_type == "order" && orderNumber == $orderNumber][0]{    _id,    orderNumber,    clerkUserId,    customerInfo{      name, email, phone,      address{ line1, line2, city, state, pincode, country }    },    lineItems[]{      _key,      productId,      productName,      colorVariant,      colorVariantSlug,      size,      qty,      priceSnapshot,      sku    },    subtotal,    shippingCost,    total,    currency,    paymentStatus,    status,    paymentId,    razorpayOrderId,    createdAt,    updatedAt  }
export type ORDER_BY_NUMBER_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  clerkUserId: string | null;
  customerInfo: {
    name: string | null;
    email: string | null;
    phone: string | null;
    address: {
      line1: string | null;
      line2: string | null;
      city: string | null;
      state: string | null;
      pincode: string | null;
      country: string | null;
    } | null;
  } | null;
  lineItems: Array<{
    _key: string;
    productId: string | null;
    productName: string | null;
    colorVariant: string | null;
    colorVariantSlug: string | null;
    size: string | null;
    qty: number | null;
    priceSnapshot: number | null;
    sku: string | null;
  }> | null;
  subtotal: number | null;
  shippingCost: number | null;
  total: number | null;
  currency: string | null;
  paymentStatus: "failed" | "paid" | "pending" | "refunded" | null;
  status:
    | "cancelled"
    | "delivered"
    | "paid"
    | "pending"
    | "processing"
    | "refunded"
    | "shipped"
    | null;
  paymentId: string | null;
  razorpayOrderId: string | null;
  createdAt: string | null;
  updatedAt: string | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ORDER_BY_RAZORPAY_ORDER_ID_QUERY
// Query: *[_type == "order" && razorpayOrderId == $razorpayOrderId][0]{    _id,    orderNumber,    paymentStatus,    status,    lineItems[]{      _key,      productId,      productName,      colorVariant,      colorVariantSlug,      size,      qty,      priceSnapshot    },    subtotal,    shippingCost,    total,    currency,    customerInfo{      name, email, phone,      address{ line1, line2, city, state, pincode, country }    }  }
export type ORDER_BY_RAZORPAY_ORDER_ID_QUERY_RESULT = {
  _id: string;
  orderNumber: string | null;
  paymentStatus: "failed" | "paid" | "pending" | "refunded" | null;
  status:
    | "cancelled"
    | "delivered"
    | "paid"
    | "pending"
    | "processing"
    | "refunded"
    | "shipped"
    | null;
  lineItems: Array<{
    _key: string;
    productId: string | null;
    productName: string | null;
    colorVariant: string | null;
    colorVariantSlug: string | null;
    size: string | null;
    qty: number | null;
    priceSnapshot: number | null;
  }> | null;
  subtotal: number | null;
  shippingCost: number | null;
  total: number | null;
  currency: string | null;
  customerInfo: {
    name: string | null;
    email: string | null;
    phone: string | null;
    address: {
      line1: string | null;
      line2: string | null;
      city: string | null;
      state: string | null;
      pincode: string | null;
      country: string | null;
    } | null;
  } | null;
} | null;

// Source: sanity/lib/queries.ts
// Variable: ORDERS_BY_USER_QUERY
// Query: *[_type == "order" && clerkUserId == $userId] | order(createdAt desc) {    _id,    orderNumber,    lineItems[]{      _key,      productName,      colorVariant,      size,      qty,      priceSnapshot    },    subtotal,    shippingCost,    total,    paymentStatus,    status,    createdAt  }
export type ORDERS_BY_USER_QUERY_RESULT = Array<{
  _id: string;
  orderNumber: string | null;
  lineItems: Array<{
    _key: string;
    productName: string | null;
    colorVariant: string | null;
    size: string | null;
    qty: number | null;
    priceSnapshot: number | null;
  }> | null;
  subtotal: number | null;
  shippingCost: number | null;
  total: number | null;
  paymentStatus: "failed" | "paid" | "pending" | "refunded" | null;
  status:
    | "cancelled"
    | "delivered"
    | "paid"
    | "pending"
    | "processing"
    | "refunded"
    | "shipped"
    | null;
  createdAt: string | null;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "heroContent" && _id == "heroContent-singleton"][0]{\n    _id,\n    eyebrow,\n    heading,\n    subtext,\n    backgroundImage,\n    ctaText,\n    ctaLink\n  }': HERO_CONTENT_QUERY_RESULT;
    '*[_type == "product" && featured == true] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    compareAtPrice,\n    "colorVariants": colorVariants[]{\n      _key,\n      name,\n      hex,\n      "slug": slug.current,\n      images[]{ _type, asset, hotspot, alt },\n      sizes[]{ _key, size, stock }\n    }\n  }': FEATURED_PRODUCTS_QUERY_RESULT;
    '*[_type == "product"] | order(_createdAt desc) {\n    _id,\n    name,\n    "slug": slug.current,\n    price,\n    compareAtPrice,\n    featured,\n    "colorVariants": colorVariants[]{\n      _key,\n      name,\n      hex,\n      "slug": slug.current,\n      images[]{ _type, asset, hotspot, alt },\n      sizes[]{ _key, size, stock }\n    },\n    "category": category->{ _id, name, "slug": slug.current }\n  }': PRODUCTS_QUERY_RESULT;
    '*[_type == "product" && slug.current == $slug][0]{\n    _id,\n    name,\n    "slug": slug.current,\n    description,\n    price,\n    compareAtPrice,\n    featured,\n    colorVariants[]{\n      _key,\n      name,\n      hex,\n      "slug": slug.current,\n      images[]{ _type, asset, hotspot, alt },\n      sizes[]{ _key, size, stock, sku }\n    },\n    "category": category->{ _id, name, "slug": slug.current },\n    tags,\n    seo{ metaTitle, metaDescription, ogImage }\n  }': PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type == "product" && defined(slug.current)]{ "slug": slug.current }': ALL_PRODUCT_SLUGS_QUERY_RESULT;
    '*[_type == "category"] | order(name asc) {\n    _id,\n    name,\n    "slug": slug.current,\n    description\n  }': CATEGORIES_QUERY_RESULT;
    '*[_type == "siteSettings" && _id == "siteSettings-singleton"][0]{\n    _id,\n    storeName,\n    supportEmail,\n    logo,\n    socialLinks,\n    footerTagline\n  }': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "product" && _id in $ids]{\n    _id,\n    name,\n    price,\n    compareAtPrice,\n    "colorVariants": colorVariants[]{\n      _key,\n      name,\n      "slug": slug.current,\n      sizes[]{ size, stock, sku }\n    }\n  }': PRODUCTS_BY_IDS_QUERY_RESULT;
    '*[_type == "order" && orderNumber == $orderNumber][0]{\n    _id,\n    orderNumber,\n    clerkUserId,\n    customerInfo{\n      name, email, phone,\n      address{ line1, line2, city, state, pincode, country }\n    },\n    lineItems[]{\n      _key,\n      productId,\n      productName,\n      colorVariant,\n      colorVariantSlug,\n      size,\n      qty,\n      priceSnapshot,\n      sku\n    },\n    subtotal,\n    shippingCost,\n    total,\n    currency,\n    paymentStatus,\n    status,\n    paymentId,\n    razorpayOrderId,\n    createdAt,\n    updatedAt\n  }': ORDER_BY_NUMBER_QUERY_RESULT;
    '*[_type == "order" && razorpayOrderId == $razorpayOrderId][0]{\n    _id,\n    orderNumber,\n    paymentStatus,\n    status,\n    lineItems[]{\n      _key,\n      productId,\n      productName,\n      colorVariant,\n      colorVariantSlug,\n      size,\n      qty,\n      priceSnapshot\n    },\n    subtotal,\n    shippingCost,\n    total,\n    currency,\n    customerInfo{\n      name, email, phone,\n      address{ line1, line2, city, state, pincode, country }\n    }\n  }': ORDER_BY_RAZORPAY_ORDER_ID_QUERY_RESULT;
    '*[_type == "order" && clerkUserId == $userId] | order(createdAt desc) {\n    _id,\n    orderNumber,\n    lineItems[]{\n      _key,\n      productName,\n      colorVariant,\n      size,\n      qty,\n      priceSnapshot\n    },\n    subtotal,\n    shippingCost,\n    total,\n    paymentStatus,\n    status,\n    createdAt\n  }': ORDERS_BY_USER_QUERY_RESULT;
  }
}
