export const PRODUCTS = [
  { id: "1", name: "Shaggy Wool Cardigan",       price: "$282.00", images: ["/products/product1.1.webp", "/products/product1.2.webp"], description: "A luxurious shaggy wool cardigan crafted for supreme warmth and texture. Features a relaxed fit, dropped shoulders, and premium horn buttons." },
  { id: "2", name: "Lightweight Turtleneck Top", price: "$92.00",  images: ["/products/product1.2.webp", "/products/product1.1.webp"], description: "An essential layering piece made from breathable, fine-gauge cotton blend. Designed with a sleek mock neck and a slightly elongated hem." },
  { id: "3", name: "Mohair Shaggy Knit",         price: "$230.00", images: ["/products/product1.3.webp", "/products/product1.4.webp"], description: "Our signature mohair knit sweater boasting an incredibly soft, brushed texture. Perfect for adding a statement texture to any outfit." },
  { id: "4", name: "Striped Waffle LS Tee",      price: "$75.00",  images: ["/products/product1.4.webp", "/products/product1.3.webp"], description: "Classic long-sleeve tee updated with a custom waffle-knit texture and subtle horizontal striping. Soft, durable, and effortlessly stylish." },
  { id: "5", name: "Cashmere Zip Sweater",       price: "$212.00", images: ["/products/product1.1.webp", "/products/product1.3.webp"], description: "Premium cashmere blend half-zip sweater. Features a chunky silver-tone zipper, ribbed cuffs, and a tailored silhouette." },
  { id: "6", name: "Ribbed Mock-Neck Sweater",   price: "$148.00", images: ["/products/product1.2.webp", "/products/product1.4.webp"], description: "Thick, ribbed-knit mock neck sweater designed for the colder months. Heavyweight construction ensures structure and warmth." },
  { id: "7", name: "Relaxed Linen Shirt",        price: "$110.00", images: ["/products/product1.3.webp", "/products/product1.1.webp"], description: "Breezy and lightweight, this relaxed linen shirt offers a perfectly draped fit. Ideal for transitional weather or layering." },
  { id: "8", name: "Wide-Leg Wool Trousers",     price: "$195.00", images: ["/products/product1.4.webp", "/products/product1.2.webp"], description: "Sophisticated wide-leg trousers tailored from a premium wool blend. Features a high waist, double pleats, and a fluid drape." },
]
